// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp_Desafio_BackEnd.DataAccess;

namespace WebApp_Desafio_BackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("WebApp_Desafio_BackEnd.Models.Chamado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Assunto")
                        .IsRequired();

                    b.Property<DateTime>("DataAbertura");

                    b.Property<int>("IdDepartamento");

                    b.Property<int>("IdSolicitante");

                    b.HasKey("ID");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdSolicitante");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("WebApp_Desafio_BackEnd.Models.Departamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("WebApp_Desafio_BackEnd.Models.Solicitante", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("ID");

                    b.ToTable("Solicitantes");
                });

            modelBuilder.Entity("WebApp_Desafio_BackEnd.Models.Chamado", b =>
                {
                    b.HasOne("WebApp_Desafio_BackEnd.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp_Desafio_BackEnd.Models.Solicitante", "Solicitante")
                        .WithMany()
                        .HasForeignKey("IdSolicitante")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
